version: '3'

services:
  simhost:
    image: uobflightlabstarling/starling-sim-iris-ap:latest
    volumes:
      - ./fenswood:/ros.env.d/fenswood
    command: ["ros2", "launch", "/ros.env.d/fenswood/iris.launch.xml"]
    ports:
      - "8080:8080"

  sitl:
    image: uobflightlabstarling/starling-sim-ardupilot-copter:latest
    environment:
      - AP_USE_GAZEBO=true
      - AP_HOME=51.4233628,-2.671671,100.0,0
    ports:
      - "18570:18570/udp"
  
  mavros:
    image: uobflightlabstarling/starling-mavros:latest
    command: ros2 launch launch/mavros_bridge.launch.xml
    environment:
      - "MAVROS_TGT_FIRMWARE=apm"
      - "MAVROS_TGT_SYSTEM=1"
      - "MAVROS_FCU_URL=tcp://127.0.0.1:5760"
      - "MAVROS_CONFIG_PATH=/mavros_config_ap.yaml"
      - "MAVROS_PLUGINLISTS_PATH=/mavros_pluginlists_ap.yaml"
    ports:
      - "5760:5760"

  rosbridge-suite:
    image: uobflightlabstarling/rosbridge-suite:latest
    ports:
      - "9090:9090"

  # Uncomment for the UI Example 
  # ui-example:
  #   image: uobflightlabstarling/starling-ui-example
  #   ports:
  #     - "3000:3000"